import { Tree } from '@nx/devkit';
import { createTreeWithEmptyWorkspace } from '@nx/devkit/testing';

import { markerGenerator } from './marker';

describe('marker generator', () => {
  let tree: Tree;

  beforeEach(() => {
    tree = createTreeWithEmptyWorkspace();
  });

  it('writes a marker file at <directory>/<name>.md with the expected body', async () => {
    await markerGenerator(tree, { name: 'foo', directory: 'tmp' });

    expect(tree.exists('tmp/foo.md')).toBe(true);
    const body = tree.read('tmp/foo.md', 'utf-8') ?? '';
    expect(body).toContain('# Marker: foo');
    expect(body).toContain('Generated by sf-plugin.');
  });

  it('interpolates the EJS <%= name %> tag instead of writing it literally', async () => {
    await markerGenerator(tree, { name: 'alpha', directory: 'out' });

    const body = tree.read('out/alpha.md', 'utf-8') ?? '';
    expect(body).not.toContain('<%=');
    expect(body).not.toContain('<%- ');
    expect(body).toMatch(/^# Marker: alpha\b/);
  });

  it('resolves the dynamic filename via the __name__ token', async () => {
    await markerGenerator(tree, { name: 'beta', directory: 'nested/path' });

    expect(tree.exists('nested/path/beta.md')).toBe(true);
    expect(tree.exists('nested/path/__name__.md')).toBe(false);
  });
});
